[program:tradingbot-api]
command=/var/www/tradingbot/venv/bin/python api.py
directory=/var/www/tradingbot
autostart=true
autorestart=true
stderr_logfile=/var/www/tradingbot/logs/api-err.log
stdout_logfile=/var/www/tradingbot/logs/api-out.log
environment=BINANCE_API_KEY="%(ENV_BINANCE_API_KEY)s",BINANCE_API_SECRET="%(ENV_BINANCE_API_SECRET)s"

[program:tradingbot-bot]
command=/var/www/tradingbot/venv/bin/python main.py
directory=/var/www/tradingbot
autostart=false
autorestart=true
stderr_logfile=/var/www/tradingbot/logs/bot-err.log
stdout_logfile=/var/www/tradingbot/logs/bot-out.log
